name: "Capture URL from issue comment"
author: "DerivFE <fe-access@deriv.com>"
description: "Capture a URL from github issue comment and feed it into your next GitHub action."

branding:
  icon: "link-2"
  color: "black"

inputs:
  cancel_pattern:
    description: "Regular expression pattern to cancel the action when comment contains this pattern."
    required: false
    default: '^((?!\[Visit Preview\]\((.*.pages.dev)\)).)*$'
  url_pattern:
    description: "Regular expression pattern to capture the URL. Ensure first capture group captures the URL."
    required: false
    default: '\[Visit Preview\]\((.*.pages.dev)\)'
  user_name:
    description: "The name of the action commenting on pull requests."
    required: false
    default: "DerivFE"
  GITHUB_TOKEN:
    description: "GitHub actions token to cancel the action in case URL could not be found. If not specified, the action will explicitly fail."
    required: false
    default: ""

outputs:
  url:
    description: "The captured URL from issue comment"
    
runs:
  using: "node16"
  main: "dist/index.js"
